### ISSUE TITLE
Stats into Jupyter module

### ISSUE THREAD

**Issue by VillemP** [VillemP/gen-toolbox#13]
Stats module has graphing and lots of data manipulation. Turn this module into a Jupyter notebook for data annotation, viewing, graphing.

**Comment by markus-marandi** [comment]
moved stats module to `gen-stats` repo

**Comment by markus-marandi** [comment]
moved stats.py module to gen-stats repo

**Comment by markus-marandi** [comment]
moved `stats.py` module to gen-stats repo
